version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-docker
    ports:
      - 80:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel_docker
      DB_USERNAME: app
      DB_PASSWORD: mysql
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: app
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379
    volumes:
      - redis-data:/data
  phpmyadmin:
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=mysql
          - PMA_USER=root
          - PMA_PASSWORD=mysql
        ports:
          - "8080:80"
        links:
          - mysql:db
        depends_on:
          - mysql
volumes:
    db-data:
      external: false
        # add internal data volume so that data persists
    redis-data:
      external: false